# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
# docs: https://git.io/JR5E4

name: 🐞 Bug report
description: File a bug/issue
labels: ['type:bug']
assignees: [tarampampam]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      multiple: true
      options:
        - Firefox
        - Chrome
        - Opera
        - Microsoft Edge
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Extension version
      placeholder: 4.x.x

  - type: textarea
    attributes:
      label: Anything else?
      description: Links? References? Anything that will give us more context about the issue you are encountering!
