name: release

on:
  release: # Docs: <https://help.github.com/en/articles/events-that-trigger-workflows#release-event-release>
    types: [published]

jobs:
  build:
    name: Build the extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: gacts/github-slug@v1
        id: slug

      - uses: actions/setup-node@v4
        with: {node-version: '20'}

      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --no-progress --non-interactive

      - name: Set the extension version
        run: yarn version --no-git-tag-version --no-commit-hooks --new-version "${{ steps.slug.outputs.version-semantic }}"

      - run: yarn build

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist.zip
          asset_name: random-user-agent.zip
          tag: ${{ github.ref }}
