name: tests

on:
  push:
    branches: [master, main]
    tags-ignore: ['**']
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: {fetch-depth: 0}

      - name: Check for GitLeaks
        uses: gacts/gitleaks@v1 # Action page: <https://github.com/gacts/gitleaks>

  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    env: {FORCE_COLOR: 'true'}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: {node-version: '20'}

      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --no-progress --non-interactive

      - run: yarn test --verbose --coverage

      - uses: codecov/codecov-action@v4 # Docs: <https://github.com/codecov/codecov-action>
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/clover.xml
          fail_ci_if_error: false

  build:
    name: Try to build
    runs-on: ubuntu-latest
    env: {FORCE_COLOR: 'true'}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: {node-version: '20'}

      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --no-progress --non-interactive

      - run: yarn build

      - uses: actions/upload-artifact@v4
        with:
          name: extension-dist
          path: dist.zip
          if-no-files-found: error
          retention-days: 1

  addons-linter:
    name: Run addon linter (mozilla)
    runs-on: ubuntu-latest
    needs: [build]
    env: {FORCE_COLOR: 'true'}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: extension-dist
          path: dist

      - uses: actions/setup-node@v4
        with: {node-version: '20'}

      - run: yarn global add addons-linter

      - run: addons-linter ./dist/dist.zip
