name: website

on:
  workflow_dispatch: {}
  push:
    branches: [master, main]
    paths: ['**.md', .github/workflows/website.yml]

concurrency:
  group: ${{ github.ref }}-website
  cancel-in-progress: true

jobs:
  update:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create jekyll config file
        env: {config: ./_config.yml}
        run: |
          echo "remote_theme: pages-themes/minimal@v0.2.0" > $config
          echo "plugins: [jekyll-remote-theme]" >> $config
          echo "title: Random User-Agent and Switcher" >> $config
          echo "baseurl: ''" >> $config
          echo "google_site_verification: RcsUxl5kqZdDhG-BU5VHhZXqwyuC6vU7PEDmMFSnbao" >> $config

      - uses: actions/configure-pages@v4

      - uses: actions/jekyll-build-pages@v1

      - uses: actions/upload-pages-artifact@v3

      - {uses: actions/deploy-pages@v4, id: deployment}
